// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdrorelvinucqalzdcho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkcm9yZWx2aW51Y3FhbHpkY2hvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzc1NjEsImV4cCI6MjA2Mzg1MzU2MX0.ETyaY5l2qB0jY69n1HwUbkEtmWt4WvWc82GULVRnKv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);